### ISSUE TITLE
Breakdown keys always empty

### ISSUE THREAD

**Issue by mikakruschel** [TelemetryDeck/Viewer#188]
Hey, I just recently added TelemetryDeck to my app and it was super easy, thanks for that! 
I just tried to create some breakdown insights and noticed that the dropdown for the metadata payload key selection is always empty, making it currently impossible to add a breakdown insight (except the default os breakdown).

<img width="247" alt="image" src="https://user-images.githubusercontent.com/20423069/151695541-5b70a1b0-4a56-4155-b16e-7624684ebd44.png">

**Comment by winsmith** [comment]
Hi, thanks for this bug report! We've noticed it ourselves and the reason is that we're using a process to pre-calculate the payload keys available for breakdown and store it in a database. Unfortunately as the amount of our customers grows, this calculation happens less and less often for each individual account.

Fortunately, we are this 🤏 close to a solution, because with our new query language we can just extract the data in real time from our datastore: no more delays at all, no more calculation jobs running in the background, and the data is always fresh.  The API for this is already on the server, and we're preparing an update to the Mac and iOS apps in the coming week.

**Comment by mikakruschel** [comment]
Even better, what a great timing 😃.

**Comment by winsmith** [comment]
Fixed with the newest release https://github.com/TelemetryDeck/Viewer/releases/tag/1.0.0b593
