### ISSUE TITLE
Error 404 when creating a Values Breakdown with `telemetryClientVersion` with Javascript SDK

### ISSUE THREAD

**Issue by Timac** [TelemetryDeck/Viewer#265]
- I use the Javascript SDK for a website with anonymous users
- Create a new insight and use a Values Breakdown with `telemetryClientVersion`

Result: In the console, you can see an error 404:

```
Failed to load resource: the server responded with a status of 404 ()
```

<img width="1093" alt="error" src="https://github.com/TelemetryDeck/Issues/assets/738543/6dc3d915-a11d-46c0-b417-034c4212d27c">

**Comment by winsmith** [comment]
This is unrelated to the JavaScript client and by design. The UI is asking the server wether a calculation result is already available and the server is answering with 404 because the value hasn't finished calculating. The 404 errors in the console are annoying but I do believe this is the correct status code to return from the API.
