### ISSUE TITLE
Improve Display of URLs in Tables

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/Viewer#336]
When displaying URLs in tables, data gets truncated in favour of URL parts (such as "https" and the host) that might not be as interesting. Find ways of displaying the more interesting parts of the URL instead. 

Interesting side note: we don't canonically know the base URL of the website we display. Might have to ask the user for that.

**Comment by cameronmcefee** [comment]
The OP mostly covers the topic, but here's some additional details.

This is what the Overview looks like for me at a fairly wide browser size on a large monitor

![Screenshot 2024-01-17 at 9 45 14 AM](https://github.com/TelemetryDeck/Issues/assets/72919/7388fa6f-a106-4904-8b29-32882015c66d)

### When thinking about urls, I have a couple motivations:

- In a breakdown of pageviews, I want to know about my pages, not the sites. As shown in the screenshot, that data isn't visible without extra effort.
- When filtering data by url, I want to be able to match paths without having to factor in the hostname. This is useful for handling test (localhost) and production data where the hostname is different. With longer paths this isn't as much of an issue with regexp, but it's hard to match the `/` path without being able to do something like `^/$`. Since I'm setting up funnels for people that come in through my home page, it's annoying to have to write overly qualified regexps to just filter home page views.

### Possible solutions:

When I originally tried sending just the path as `url` it showed up in the interface as `:///my-path` which functionally resolved the problem, but is ugly. In thinking through my own solution for this, I've started considering sending the URL *and* the path with my signal. I can use the path for filtering because it has no particular significance to TelemetryDeck so it won't get mutated like the url does.

The downside of this is that I imagine the Overview won't pick that up, so I'll need to make my own Insight to view that. Not terrible, but not natively supported.

From a product-first perspective, that might be a solution. When ingesting urls, create an extra path value that can be used for filtering. That feels like a fairly clean solution that wouldn't require adding something like a "only apply to path" or "include host in graph" options.

> Interesting side note: we don't canonically know the base URL of the website we display. Might have to ask the user for that.

I know some services ask you which urls you load your tracking script on, but I'm not sure you'd actually half to do that. If you were to parse the url into more pieces (base url, path, maybe utms if present) and shove that into the signal data, then you could just set up filters for those bits.

**Comment by winsmith** [comment]
Huh, actually including the path in the SDK definitely sounds like the easiest solution to this problem!  Actually, we do a lot of URL parsing in the ingest API anyway. Let me try this out.

**Comment by winsmith** [comment]
Update: The ingest API, when receiving signals from the Web SDK, now extracts these properties: 

- `host` e.g. `telemetrydeck.com`
- `path` e.g. `/blog/` or `/` or `` (the last two are distinct paths in the HTTP spec)
- `schema` e.g. `https`

If you build your own TopN (breakdown) query, this is what this looks like:

<img width="508" alt="Screenshot 2024-01-18 at 14 36 23" src="https://github.com/TelemetryDeck/Issues/assets/954120/e1faa426-3fe4-45aa-b447-7175e9016007">

Can you work with that? I think I'll add a lil switcher to the dashboard to switch the default insight between URLs and Paths

**Comment by cameronmcefee** [comment]
Yep, I think that works great! Thanks for the improvement :pray:
