### ISSUE TITLE
Website tracking: v6 hover on "Visitors" shows empty popover

### ISSUE THREAD

**Issue by DivineDominion** [TelemetryDeck/Viewer#411]
Visitors:
![2024-06-28 19-38-56 Arc - christiantietze de  TelemetryDeck@2x](https://github.com/TelemetryDeck/Issues/assets/59080/c61cba3c-448e-49c3-af49-bcc7c8d6c66a)

WebSDK for comparison:
![2024-06-28 19-41-36 Arc - christiantietze de  TelemetryDeck@2x](https://github.com/TelemetryDeck/Issues/assets/59080/4b39caa3-7a25-4043-966c-290f079053c0)

**Comment by Jeehut** [comment]
@DivineDominion First of all, thank you for reporting this issue! I just wanted to investigate it and tried to reproduce it, but I couldn't. No matter if there were 0 visitors or if I tried on an app or website, it seemed to work. Maybe it got fixed by now? Can you please check and provide more context information so I can reproduce and fix this if it still happens! Thank you!

**Comment by DivineDominion** [comment]
Seems to be fixed since then
